name: webapp
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html

  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3308:3306"
# CAMBIAR POR EL ID DE TU USUARIO
    user: IDusuario:IDusuario
    environment:
# TU CONTRASEÑA SUPER SEGURA
      MARIADB_ROOT_PASSWORD: USUARIO
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

